# Ensure devDependencies are installed so Vite is available during build
[phases.install]
commands = [
  "npm ci --include=dev"
]

[phases.build]
commands = [
  "npm run build"
]

[start]
cmd = "serve -s dist -p $PORT"

[variables]
# Prevent npm from pruning devDependencies in production builds
NPM_CONFIG_PRODUCTION = "false"
PORT = "80"
