# Ensure devDependencies are installed so Vite is available during build
[phases.install]
commands = [
  "npm ci --include=dev"
]

[phases.build]
commands = [
  "npm run build"
]

[variables]
# Prevent npm from pruning devDependencies in production builds
NPM_CONFIG_PRODUCTION = "false"
